
[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root
# user=nobody

[program:llm-server]
command=python3 -m llama_cpp.server --config_file config-gpt.json
# directory=/home/azadmin/gguf_runtime/phi-3-mini-4k-gguf
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/llm-server.err.log
stdout_logfile=/var/log/supervisor/llm-server.out.log
priority=100
startsecs=10

[program:proxy-server]
command=python3 llm_proxy_server.py
# directory=/home/azadmin/gguf_runtime/phi-3-mini-4k-gguf
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/proxy-server.err.log
stdout_logfile=/var/log/supervisor/proxy-server.out.log
priority=200
startsecs=15
depends_on=llm-server